#!/bin/bash

# System Info
# shellcheck disable=SC2034
SYSTEM_NAME="Service Manager System"
SYSTEM_VERSION="1.0.0"
SYSTEM_AUTHOR="jjolisrp"

# Directories
BASE_DIRECTORY="$SCRIPT_DIR"
LIB_DIRECTORY="$BASE_DIRECTORY/lib"
MODULES_DIRECTORY="$BASE_DIRECTORY/modules"
CONFIG_DIRECTORY="$BASE_DIRECTORY/config"
LOGS_DIRECTORY="$BASE_DIRECTORY/logs"
BACKUPS_DIRECTORY="$BASE_DIRECTORY/backups"